### PR TITLE
IE 11 fix

### PR DESCRIPTION
**Pull request by hasnat**
somehow IE 11 cannot resolve this.props even after super so better be using props instead of this.props

### CODE REVIEW

**Comment by tleunen** [comment]
Good catch @hasnat! Thanks

**Comment by hasnat** [comment]
Thanks for the merge, when are you planning to release this to npm?

**Comment by tleunen** [comment]
Yes absolutely! ;)
I'd like to go through the other pending PR before, so probably releasing the new version in the evening.

**Comment by hasnat** [comment]
good man, 
Thanks

**Pull request merged**
